apiVersion: apps/v1
kind: Deployment
metadata: 
 name: mongo 
 namespace: policy-claims
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo
  template:
    metadata: 
      labels: 
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mypvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mypvc
  namespace: policy-claims
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: policy-claims
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP