apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-secrets
  namespace: policy-claims
type: Opaque
stringData:
  JWT_SECRET: policy-claims-secret
  MONGODB_URI: mongodb://mongo:27017/policy-claims